
version: 2

models:
  - name: blocks
    description: "Harmony Blocks"
    columns:
      - name: block_id
        description: The block height
        tests:
          - unique
          - not_null
      - name: block_timestamp
        description: The time the block was minted
        tests:
          - unique
          - not_null
      - name: block_hash
        description: The hash of the block
        tests:
          - unique
          - not_null
      - name: block_parent_hash
        description: The hash of the parent block
        tests:
          - unique
          - not_null
      - name: gas_limit
        description: The gas limit for the block
        tests:
          - not_null
      - name: gas_used
        description: The amount of gas used by the block
        tests:
          - not_null
      - name: miner
        description: The miner that minted this block
        tests:
          - not_null
      - name: miner
        description: The size of the block
        tests:
          - not_null
      - name: tx_count
        description: The number of transactions in this block.

  - name: txs
    description: "Harmony Transactions"
    columns:
      - name: tx_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
